### ISSUE TITLE
Cannot find module 'handlebars'

### ISSUE THREAD

**Issue by frank3manuel** [rjaviervega/ember-xmpp-im#2]
I reinstalled node from scratch, pulled a clean copy of the project, and executed the instructed npm install and bower install. 

ember -v:
version: 0.1.2
node: 5.4.1
npm: 2.1.3

Trying to start the server returns this error.

ember server:
version: 0.1.2
Cannot find module 'handlebars'
Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/admin/Sites/ember_new/node_modules/ember-template-compiler/vendor/ember-template-compiler.js:29:16
    at Object.<anonymous> (/Users/admin/Sites/ember_new/node_modules/ember-template-compiler/vendor/ember-template-compiler.js:327:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

I recall that the previous version of node (0.12.7) did not have this problem.

Is there a specific version of node that I should be using?

Thanks,
Frank

**Comment by frank3manuel** [comment]
Solved by installing nvm and reverting to node version 0.12.7.

**Comment by jakeperry** [comment]
npm WARN peerDependencies The peer dependency handlebars@~1 included from ember-template-compiler will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

Here is the reason it can't be installed on the latest Node and npm
